In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
#Load dataset
df=pd.read_csv("boston_housing.csv.csv")
#View dimension of dataset
df.shape

(506, 14)

In [2]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,price
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [3]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,price
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
df_x=df
print(df_x)

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273

     ptratio   black  lstat  price
0       15.3  396.90   4.98   24.0
1       17.8  396.90   9.14   21.6
2       17.8  392.83   4.03   34.7
3       18.7  394.63   2.94   33.4
4       18.7  396.90   5.33   36.2
..       ...     ...    ...    ...
501     21.0  391.99   9.67   22.4
502     21.0  396.90   9.08   20.6
503     21.0  396.90   5.64   23.9
504     21.0  393.45   6.48   22.0
505     21.0  396.90   7.88   11.9

[506 rows x 14 columns]

In [5]:
df_y=df
print(df_y)

        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273

     ptratio   black  lstat  price
0       15.3  396.90   4.98   24.0
1       17.8  396.90   9.14   21.6
2       17.8  392.83   4.03   34.7
3       18.7  394.63   2.94   33.4
4       18.7  396.90   5.33   36.2
..       ...     ...    ...    ...
501     21.0  391.99   9.67   22.4
502     21.0  396.90   9.08   20.6
503     21.0  396.90   5.64   23.9
504     21.0  393.45   6.48   22.0
505     21.0  396.90   7.88   11.9

[506 rows x 14 columns]

In [6]:
from sklearn.linear_model import LinearRegression
reg =LinearRegression()
#Split the data into 67% training and 33% testing data
#NOTE: We have to split the dependent variables (x) and the target or independent variable (y)
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.33, random_state=42)
#Train our model with the training data
reg.fit(x_train, y_train)
#Print the coefecients/weights for each feature/column of our model
print(reg.coef_)

[[ 1.00000000e+00 -3.94798382e-18 -9.59705535e-17 -4.72631346e-16
  -9.43109696e-15  5.18287178e-16  1.67124563e-16 -1.01864422e-16
  -1.12668222e-16  5.56595056e-17 -1.79484875e-16 -5.08928626e-17
  -4.64206131e-16  4.18484423e-16]
 [ 3.23868495e-15  1.00000000e+00  2.51187959e-15  1.38238352e-14
   2.42540905e-14  2.88441146e-15  1.80411242e-16  8.48279780e-16
  -3.47638585e-15 -2.22044605e-16 -4.86589935e-16 -1.05471187e-15
  -2.84494650e-16  6.66133815e-16]
 [-2.16507814e-16 -7.63278329e-17  1.00000000e+00 -4.17419107e-16
   1.38487142e-14 -2.65839596e-16  6.54858112e-17  1.15936449e-15
   1.15575952e-16  1.94289029e-16 -9.15879785e-17  6.02816408e-16
  -6.61363325e-17 -2.05456312e-16]
 [-1.01474457e-17  5.54298361e-18 -1.54707603e-16  1.00000000e+00
  -1.23002110e-14 -4.96677568e-16  1.03717490e-16 -1.57292642e-16
   2.25571650e-16  3.13063377e-17  3.32784634e-16  1.50927719e-16
  -4.88301789e-17 -3.29855805e-17]
 [-6.58686370e-17  9.07477218e-17  7.26415456e-17 -3.01827531e-15
   1.00000000e+00 -2.07315051e-15 -7.75136791e-17  1.21169757e-16
   2.71802708e-16 -1.32272665e-17  2.89244811e-17  1.08420217e-19
  -1.74827600e-17 -1.55867615e-16]
 [-7.12395872e-17  1.91253263e-16 -1.00403897e-16  2.20549886e-15
  -1.20719083e-15  1.00000000e+00  4.26904605e-17 -4.36933476e-17
   4.45701961e-16 -2.29850861e-17 -9.65414272e-17 -5.74627151e-18
   1.76589429e-17 -4.30631550e-16]
 [-1.78446505e-15  1.52655666e-16 -2.22478286e-16 -1.48544270e-14
  -4.78721067e-14 -4.65632307e-15  1.00000000e+00  5.12719207e-16
  -8.93382590e-17  5.27355937e-16 -4.96564595e-17  1.26287869e-15
  -4.77048956e-17  4.64472211e-16]
 [ 2.62827536e-17 -6.93889390e-18 -4.72712147e-17  3.38113223e-15
  -1.15734220e-15 -3.14962425e-16 -1.17093835e-17  1.00000000e+00
  -8.00683304e-17 -4.25007252e-17 -2.44778969e-16 -7.24247051e-17
  -1.56531689e-16 -2.63461128e-16]
 [-6.30472943e-16  6.93889390e-18  5.55328353e-16 -1.60478744e-14
  -2.45033079e-15  8.25674164e-16 -3.60822483e-16 -5.88504939e-16
   1.00000000e+00 -2.77555756e-17 -1.29562160e-16 -1.89084859e-16
   7.80625564e-18 -7.93635990e-17]
 [-5.47413462e-15 -5.55111512e-16 -2.83800761e-15  5.20769408e-16
  -1.25834673e-14  3.46294174e-15  5.55111512e-17 -5.59448321e-16
  -4.71844785e-15  1.00000000e+00 -6.44449771e-16 -6.66133815e-16
  -3.85108612e-16 -3.88578059e-16]
 [-1.12555093e-16 -7.37257477e-17 -2.42861287e-17 -2.07173999e-15
  -3.15935581e-15 -5.26385237e-16 -6.49437101e-17 -1.51029363e-16
   6.93889390e-18  1.12757026e-17  1.00000000e+00  1.08420217e-18
  -5.83842870e-17 -6.17724188e-17]
 [ 3.55058968e-15 -3.88578059e-16 -1.03129311e-15 -3.07447989e-14
  -1.46931621e-14 -5.89155461e-16  1.97758476e-16  8.66928057e-16
  -5.91540705e-16 -6.10622664e-16 -8.45677695e-17  1.00000000e+00
  -1.27502175e-16  2.56739074e-16]
 [-2.94672373e-16 -1.21430643e-16  1.48871800e-15 -1.18556906e-14
   9.01251187e-15  1.01088300e-16 -2.15105711e-16  4.51434680e-16
  -5.00250882e-16  7.28583860e-17  2.06594724e-16  8.50014503e-17
   1.00000000e+00  6.70687464e-16]
 [ 1.34299810e-15  3.46944695e-16 -6.00648004e-16  9.86199656e-15
   1.55348553e-14 -2.13683373e-15  2.06865775e-16  1.01611428e-15
   5.68555619e-16 -1.00613962e-16  5.34186410e-16 -2.42861287e-17
   1.05319399e-15  1.00000000e+00]]

In [7]:
y_pred = reg.predict(x_test)
print(y_pred)

[[ 9.17800000e-02 -1.89665704e-14  4.05000000e+00 ...  3.95500000e+02
   9.04000000e+00  2.36000000e+01]
 [ 5.64400000e-02  4.00000000e+01  6.41000000e+00 ...  3.96900000e+02
   3.53000000e+00  3.24000000e+01]
 [ 1.05740000e-01 -5.01914298e-14  2.77400000e+01 ...  3.90110000e+02
   1.80700000e+01  1.36000000e+01]
 ...
 [ 7.61620000e-01  2.00000000e+01  3.97000000e+00 ...  3.92400000e+02
   1.04500000e+01  2.28000000e+01]
 [ 1.00245000e+00  1.00380419e-14  8.14000000e+00 ...  3.80230000e+02
   1.19800000e+01  2.10000000e+01]
 [ 5.20140000e-01  2.00000000e+01  3.97000000e+00 ...  3.86860000e+02
   5.91000000e+00  4.88000000e+01]]

In [8]:
y_pred[0]

array([ 9.17800000e-02, -1.89665704e-14,  4.05000000e+00,  3.73443588e-15,
        5.10000000e-01,  6.41600000e+00,  8.41000000e+01,  2.64630000e+00,
        5.00000000e+00,  2.96000000e+02,  1.66000000e+01,  3.95500000e+02,
        9.04000000e+00,  2.36000000e+01])

In [9]:
y_test[0]

KeyError: 0